### ISSUE TITLE
ObjectHash casing

### ISSUE THREAD

**Issue by andys8** [arnau/elm-objecthash#1]
https://github.com/arnau/elm-objecthash/blob/42eb33e0c89bdb9ffa8bcc5f293e56713ad7fa7f/src/ObjectHash.elm#L1

This line is working fine with 0.19.0, but will lead to an error with upcoming Elm version 0.19.1

```
-- MODULE NAME MISMATCH ------------------------------------- src/ObjectHash.elm

It looks like this module name is out of sync:

1| module Objecthash exposing (objecthash, fromJson)
          ^^^^^^^^^^
I need it to match the file path, so I was expecting to see `ObjectHash` here.
Make the following change, and you should be all set!

    Objecthash -> ObjectHash

Note: I require that module names correspond to file paths. This makes it much
easier to explore unfamiliar codebases! So if you want to keep the current
module name, try renaming the file instead.
```

**Comment by arnau** [comment]
Nice catch, thanks! Wouldn't changing the file name be less aggressive than changing the actual module name? mmm, not sure it is a breaking change anyway

**Comment by andys8** [comment]
Hey, you're right, Changing the module name instead should be better aligned with `elm.json`.

**Comment by andys8** [comment]
Could you add the change and publish the package? Keep in mind it might be tricky to change this when working with mac or windows (case insensitive filesystems).

https://stackoverflow.com/a/24979063

Want to remove all failing packages, see: https://github.com/andys8/elm-compiler-test/

**Comment by arnau** [comment]
Will do as soon as I can 👍

**Comment by arnau** [comment]
@andys8 2.2.1 released
